name: "South HIL"
description: "Setup integration tests for the S2OUTH Project"
inputs:
  binary-file:
    required: true
    description: The path to the binary file
  fw-version:
    required: true
    description: The firmware version baked into the binary
  fw-hash:
    required: true
    description: The firmware hash baked into the binary
  probe-rs-version:
    required: false
    default: "v0.31.0"
    description: The version of probe-rs used
  labgrid-coordinator-addr:
    required: false
    default: "labgrid-coordinator:20408"
    description: The labgrid address and port

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: "pip"
        cache-dependency-path: |
          ${{ github.action_path }}/requirements.txt

    - name: Show firmware version vars
      shell: bash
      run: |
        echo "FW_VERSION=$FW_VERSION"
        echo "FW_HASH=$FW_HASH"

    - name: Setup probe-rs
      uses: S2outh/setup-probe-rs-action@v1
      with:
        version: ${{ inputs.probe-rs-version }}

    - name: Write labgrid env.yaml from secret
      shell: bash
      run: |
        mkdir -p pytest
        cat > env.yaml <<'EOF'
        ${{ secrets.LABGRID_ENV }}
        EOF
        chmod 600 env.yaml

    - name: Run tests
      shell: bash
      env:
        BINARY: ${{ inputs.binary-file }}
        FW_VERSION: ${{ inputs.fw-version }}
        FW_HASH: ${{ inputs.fw-hash }}
        LG_COORDINATOR: ${{ inputs.labgrid-coordinator-addr }}
      run: |
        cd ${{ github.action_path }}
        pytest -q --capture=tee-sys --junitxml=test-results/junit.xml

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: junit-results
        path: test-results/junit.xml

    - name: Publish test report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: pytest
        path: test-results/junit.xml
        reporter: java-junit
