name: "South HIL"
description: "Setup integration tests for the S2OUTH Project"
inputs:
  binary-file:
    required: true
    description: The path to the binary file
outputs:
  install_root:
    value: ${{ steps.install.outputs.install_root }}
    description: Where probe rs was installed
  bin_dir:
    value: ${{ steps.install.outputs.bin_dir }}
    description: Bin dir

# runs:
#   using: "composite"
#   steps:
#     - id: install
#       shell: bash
#       env:
#         PROBE_RS_VERSION: ${{ inputs.version }}
#         PROBE_RS_INSTALL_ROOT: ${{ inputs.install-root }}
#         PROBE_RS_GIT_URL: ${{ inputs.git-url }}
#         PROBE_RS_FEATURES: ${{ inputs.features }}
#       run: |
#         bash "${{ github.action_path }}/scripts/install-probe-rs.sh"
