name: "South HIL"
description: "Setup integration tests for the S2OUTH Project"
inputs:
  probe-name:
    required: true
    description: the name of the target probe to be flashed
  binary-file:
    required: true
    description: The path to the binary file
  fw-version:
    required: true
    description: The firmware version baked into the binary
  fw-hash:
    required: true
    description: The firmware hash baked into the binary
  probe-rs-version:
    required: false
    default: "v0.31.0"
    description: The version of probe-rs used
  labgrid-coordinator-addr:
    required: false
    default: "labgrid-coordinator:20408"
    description: The labgrid address and port
  labgrid-env:
    required: true

runs:
  using: "composite"
  steps:
    - name: Copy test files to workspace
      shell: bash
      run: |
        cp "${{ github.action_path }}/requirements.txt" "${{ github.workspace }}/"
        cp "${{ github.action_path }}/pyproject.toml" "${{ github.workspace }}/"
        cp -r "${{ github.action_path }}/pytest" "${{ github.workspace }}/"

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: "pip"
        cache-dependency-path: |
          ${{ github.workspace }}/requirements.txt

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup probe-rs
      uses: S2outh/setup-probe-rs-action@v1
      with:
        version: ${{ inputs.probe-rs-version }}

    - name: Run tests
      shell: bash
      env:
        PROBE_NAME: ${{ inputs.probe-name }}
        BINARY: ${{ inputs.binary-file }}
        FW_VERSION: ${{ inputs.fw-version }}
        FW_HASH: ${{ inputs.fw-hash }}
        LG_COORDINATOR: ${{ inputs.labgrid-coordinator-addr }}
        LABGRID_ENV: ${{ inputs.labgrid-env }}
      run: |
        echo "FW_VERSION=$FW_VERSION"
        echo "FW_HASH=$FW_HASH"

        mkdir -p pytest
        printf "%s" "$LABGRID_ENV" > env.yaml
        chmod 600 env.yaml

        pytest -q --capture=tee-sys --junitxml=test-results/junit.xml

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: junit-results
        path: test-results/junit.xml

    - name: Publish test report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: pytest
        path: test-results/junit.xml
        reporter: java-junit
